[package]
name = "iracing-simulation"
version = "0.1.0"
description = "iRacing Simulation helpers"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.dist]
dist = false

[dev-dependencies]
reqwest = { version = "0.13", features = ["blocking"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
ureq = "3"

[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
