[package]
name = "iracing-sdk-adapter"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
csv = "1.4.0"
iracing-sdk = { path = "../iracing-sdk" }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[dev-dependencies]
criterion = "0.8.2"
proptest = "1.7.0"
test-utils = { path = "../test-utils" }

[features]
benchmark = []

[[bench]]
name = "frame_construction"
harness = false
required-features = ["benchmark"]

[[example]]
name = "disk-position"
path = "examples/disk_position.rs"

[[example]]
name = "live-position"
path = "examples/live_position.rs"

[[example]]
name = "enum-bitfields-live"
path = "examples/enum_bitfields_live.rs"
