[workspace]

members = [
  "crates/iracing-sdk",
  "crates/iracing-sdk-codegen",
  "crates/iracing-sdk-adapter",
  "crates/iracing-simulation",
  "crates/test-utils",
]

resolver = "3"

[workspace.package]
authors = ["Justin Makaila <justin@treehousetechnology.io>"]
repository = "https://github.com/racedirector/iracing.rs"
homepage = "https://github.com/racedirector/iracing.rs"
license = "MIT"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.59", features = ["derive"] }
schemars = { version = "1.2", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1" }
serde_yaml_ng = "0.10"
thiserror = "2.0.16"
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[workspace.metadata.dist]
cargo-dist-version = "0.30.4"
ci = ["github"]
installers = ["homebrew"]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "aarch64-apple-darwin",
]
hosting = ["github"]
tap = "racedirector/homebrew-tap"
publish-jobs = ["homebrew"]
allow-dirty = ["ci"]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
