allowBuilds:
  '@bufbuild/buf': set this to true or false
  "@nestjs/core": true
  "@openapitools/openapi-generator-cli": true
  esbuild: true
  grpc-tools: set this to true or false
  protobufjs: true
