[package]
name = "iracing-broadcast-cli"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
iracing-broadcast-sdk = { workspace = true }
iracing-sdk = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "iracing-broadcast"
path = "src/main.rs"
