[alias]
test-fixtures = ["run", "-p", "test-fixtures", "--"]

broadcast = ["run", "-p", "iracing-sdk", "--bin", "broadcast", "--"]

ibt-read-frame = [
  "run",
  "-p",
  "iracing-sdk",
  "--example",
  "ibt-read-frame",
  "--",
]

manual-frame-adapter = [
  "run",
  "-p",
  "iracing-sdk",
  "--example",
  "manual-frame-adapter",
  "--",
]

ibt-subscribe = ["run", "-p", "iracing-sdk", "--example", "ibt-subscribe", "--"]

live-subscribe = [
  "run",
  "-p",
  "iracing-sdk",
  "--example",
  "live-subscribe",
  "--",
]

enum-bitfields-ibt = [
  "run",
  "-p",
  "iracing-sdk",
  "--example",
  "enum-bitfields-ibt",
  "--",
]

car-setup-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "car-setup-schema",
  "--",
]

disk-variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "disk-variable-schema",
  "--",
]

headers = ["run", "-p", "iracing-sdk", "--bin", "headers", "--"]

ibt-to-csv = ["run", "-p", "iracing-sdk", "--bin", "ibt-to-csv", "--"]

ibt-json-snapshot = [
  "run",
  "-p",
  "iracing-sdk",
  "--bin",
  "ibt-json-snapshot",
  "--",
]

ibt-to-json = ["run", "-p", "iracing-sdk", "--bin", "ibt-to-json", "--"]

primitives-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "primitives-schema",
  "--",
]

live-to-csv = ["run", "-p", "iracing-sdk", "--bin", "live-to-csv", "--"]

live-json-snapshot = [
  "run",
  "-p",
  "iracing-sdk",
  "--bin",
  "live-json-snapshot",
  "--",
]

live-to-jsonl = ["run", "-p", "iracing-sdk", "--bin", "live-to-jsonl", "--"]

live-variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "live-variable-schema",
  "--",
]

session = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "session",
  "--",
]

session-updates = [
  "run",
  "-p",
  "iracing-sdk",
  "--example",
  "session-updates",
  "--",
]

variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen,schema-discovery",
  "--bin",
  "variable-schema",
  "--",
]
