[alias]
broadcast-cli = ["run", "-p", "iracing-sdk", "--bin", "broadcast-cli", "--"]

car-setup-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "car-setup-schema",
  "--",
]

disk-session-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "disk-session-schema",
  "--",
]

disk-variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "disk-variable-schema",
  "--",
]

ibt-headers = ["run", "-p", "iracing-sdk", "--bin", "ibt-headers", "--"]

ibt-session-parser = [
  "run",
  "-p",
  "iracing-sdk",
  "--bin",
  "ibt-session-parser",
  "--",
]

ibt-to-csv = ["run", "-p", "iracing-sdk", "--bin", "ibt-to-csv", "--"]

iracing-primitives-schema = [
  "run",
  "-p",
  "iracing-sdk-codegen",
  "--bin",
  "iracing-primitives-schema",
  "--",
]

live-headers = ["run", "-p", "iracing-sdk", "--bin", "live-headers", "--"]

live-session-parser = [
  "run",
  "-p",
  "iracing-sdk",
  "--bin",
  "live-session-parser",
  "--",
]

live-session-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--bin",
  "live-session-schema",
  "--",
]

live-to-csv = ["run", "-p", "iracing-sdk", "--bin", "live-to-csv", "--"]

live-variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "live-variable-schema",
  "--",
]

session-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "session-schema",
  "--",
]

variable-schema = [
  "run",
  "-p",
  "iracing-sdk",
  "--features",
  "codegen",
  "--bin",
  "variable-schema",
  "--",
]
