//! Declaration macros shared by the IRSDK type modules.

macro_rules! sdk_enum {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $($variant:ident = $value:expr,)+
        }
    ) => {
        $(#[$meta])*
        #[repr(i32)]
        #[derive(
            Debug,
            Clone,
            Copy,
            PartialEq,
            Eq,
            Hash,
            serde::Serialize,
            serde::Deserialize,
        )]
        $vis enum $name {
            $(
                #[doc = concat!("SDK member `", stringify!($variant), "`.")]
                $variant = $value,
            )+
        }

        impl TryFrom<i32> for $name {
            type Error = i32;

            fn try_from(value: i32) -> Result<Self, Self::Error> {
                match value {
                    $($value => Ok(Self::$variant),)+
                    raw => Err(raw),
                }
            }
        }

        impl From<$name> for i32 {
            fn from(value: $name) -> Self {
                value as i32
            }
        }

        impl Default for $name {
            fn default() -> Self {
                Self::try_from(0).expect(concat!(stringify!($name), " must define value 0"))
            }
        }

        #[cfg(feature = "codegen")]
        impl $name {
            /// Named variants and their SDK values for schema generation.
            pub const SCHEMA_VALUES: &'static [(&'static str, i64)] = &[
                $((stringify!($variant), $value as i64),)+
            ];
        }

        #[cfg(feature = "codegen")]
        impl schemars::JsonSchema for $name {
            fn schema_name() -> std::borrow::Cow<'static, str> {
                stringify!($name).into()
            }

            fn schema_id() -> std::borrow::Cow<'static, str> {
                concat!(module_path!(), "::", stringify!($name)).into()
            }

            fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {
                #[allow(dead_code, clippy::enum_variant_names)]
                #[derive(schemars::JsonSchema)]
                $(#[$meta])*
                enum SchemaRepresentation {
                    $($variant,)+
                }

                let mut schema = SchemaRepresentation::json_schema(generator);
                let schema_object = schema.ensure_object();
                schema_object.insert("x-irsdk-kind".into(), "enum".into());
                schema_object.insert(
                    "x-irsdk-values".into(),
                    $crate::codegen::named_schema_values(Self::SCHEMA_VALUES),
                );
                schema
            }
        }
    };
}

pub(crate) use sdk_enum;

#[cfg(test)]
mod tests {
    use std::mem::{align_of, size_of};

    sdk_enum! {
        /// Enum used to exercise the code generated by `sdk_enum!`.
        enum TestEnum {
            Negative = -2,
            Zero = 0,
            Positive = 7,
        }
    }

    #[test]
    fn enum_uses_i32_representation_and_round_trips_known_values() {
        assert_eq!(size_of::<TestEnum>(), size_of::<i32>());
        assert_eq!(align_of::<TestEnum>(), align_of::<i32>());

        for (raw, value) in [
            (-2, TestEnum::Negative),
            (0, TestEnum::Zero),
            (7, TestEnum::Positive),
        ] {
            assert_eq!(TestEnum::try_from(raw), Ok(value));
            assert_eq!(i32::from(value), raw);
        }
    }

    #[test]
    fn enum_rejects_unknown_values_without_losing_the_raw_value() {
        assert_eq!(TestEnum::try_from(-1), Err(-1));
        assert_eq!(TestEnum::try_from(i32::MAX), Err(i32::MAX));
    }
}
