[package]
name = "iracing-sdk-codegen"
version = "0.1.0"
description = "Code generation binaries for iracing-sdk"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.dist]
dist = true


[package.metadata.dist.bin.live-variable-schema]
targets = ["x86_64-pc-windows-msvc"]

[package.metadata.dist.bin.live-session-schema]
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
iracing-sdk = { path = "../iracing-sdk", features = [
  "codegen",
  "schema-discovery",
] }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[[bin]]
name = "iracing-primitives-schema"
path = "src/bin/iracing_primitives_schema.rs"
