[package]
name = "iracing-irsdk"
version = "0.1.0"
description = "Rust representations of the native iRacing SDK wire contract"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
type-layout = { workspace = true, optional = true }
zerocopy = { workspace = true }

[dependencies.bitflags]
version = "2.13.2"
features = ["serde"]

[dev-dependencies]
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }

[features]
default = []
serde = ["dep:serde"]
debug = ["dep:type-layout"]
broadcast = []
