[package]
name = "iracing-broadcast-grpc-service"
version = "0.1.0"
description = "iRacing SDK Broadcast Service for gRPC"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
autobins = false

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
iracing-sdk = { version = "0.1.0", path = '../iracing-sdk' }
prost = "0.14"
socket2 = "0.6"
thiserror = { workspace = true }
tokio = { version = "1.0", features = [
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic-prost = "0.14"
tonic = "0.14"
tonic-health = "0.14"
tonic-reflection = "0.14"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build = "0.14"

[[bin]]
name = "iracing-broadcast-server"
path = "src/bin/server.rs"
